// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1dail5vdGpSylJ_wuoJBXSQQwFxWnvoE',
    appId: '1:691132595156:web:2caa75dd34f1247759b441',
    messagingSenderId: '691132595156',
    projectId: 'health-hta-app',
    authDomain: 'health-hta-app.firebaseapp.com',
    storageBucket: 'health-hta-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsT8obMCtqp3lnfSZtIwE7U7QHxnWTV1k',
    appId: '1:691132595156:android:a53276133bf29b8959b441',
    messagingSenderId: '691132595156',
    projectId: 'health-hta-app',
    storageBucket: 'health-hta-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGS_xjkyn6lgUr0B0lOtJ7KqGxEU8f66c',
    appId: '1:691132595156:ios:57455ed4f0f0ed3c59b441',
    messagingSenderId: '691132595156',
    projectId: 'health-hta-app',
    storageBucket: 'health-hta-app.firebasestorage.app',
    iosBundleId: 'com.example.hypnotherapistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGS_xjkyn6lgUr0B0lOtJ7KqGxEU8f66c',
    appId: '1:691132595156:ios:57455ed4f0f0ed3c59b441',
    messagingSenderId: '691132595156',
    projectId: 'health-hta-app',
    storageBucket: 'health-hta-app.firebasestorage.app',
    iosBundleId: 'com.example.hypnotherapistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1dail5vdGpSylJ_wuoJBXSQQwFxWnvoE',
    appId: '1:691132595156:web:167a39a9ba8e599b59b441',
    messagingSenderId: '691132595156',
    projectId: 'health-hta-app',
    authDomain: 'health-hta-app.firebaseapp.com',
    storageBucket: 'health-hta-app.firebasestorage.app',
  );
}
